//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentAdder.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentAdder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здійснюється додавання та фільтрація данних.
        /// </summary>
        public static string AboutProgramDescription {
            get {
                return ResourceManager.GetString("AboutProgramDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати.
        /// </summary>
        public static string AddFTPBtnAdd {
            get {
                return ResourceManager.GetString("AddFTPBtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відміна.
        /// </summary>
        public static string AddFTPBtnCancel {
            get {
                return ResourceManager.GetString("AddFTPBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть Логін від цього FTP-сховища:*.
        /// </summary>
        public static string AddFTPLoginName {
            get {
                return ResourceManager.GetString("AddFTPLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть пароль від цього FTP-сховища:*.
        /// </summary>
        public static string AddFTPPasswordName {
            get {
                return ResourceManager.GetString("AddFTPPasswordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть FTP-шлях до сховища:.
        /// </summary>
        public static string AddFTPPathName {
            get {
                return ResourceManager.GetString("AddFTPPathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на *Залиште поля логіна та пароля пустими, якщо вони не потрібні..
        /// </summary>
        public static string AddFTPSomeNote {
            get {
                return ResourceManager.GetString("AddFTPSomeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати новий FTP-репозиторій.
        /// </summary>
        public static string AddFTPWindowTitle {
            get {
                return ResourceManager.GetString("AddFTPWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строка підключення до БД:.
        /// </summary>
        public static string DatabaseStngConnectStr {
            get {
                return ResourceManager.GetString("DatabaseStngConnectStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я (назва) бази даних.
        /// </summary>
        public static string DatabaseStngDbName {
            get {
                return ResourceManager.GetString("DatabaseStngDbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логін:.
        /// </summary>
        public static string DatabaseStngLogin {
            get {
                return ResourceManager.GetString("DatabaseStngLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль:.
        /// </summary>
        public static string DatabaseStngPassword {
            get {
                return ResourceManager.GetString("DatabaseStngPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата додавання.
        /// </summary>
        public static string MainDataGridFileAddDate {
            get {
                return ResourceManager.GetString("MainDataGridFileAddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шлях до файлу.
        /// </summary>
        public static string MainDataGridFilePath {
            get {
                return ResourceManager.GetString("MainDataGridFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип файлу.
        /// </summary>
        public static string MainDataGridFileType {
            get {
                return ResourceManager.GetString("MainDataGridFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стартова.
        /// </summary>
        public static string MainFirstTabHeader {
            get {
                return ResourceManager.GetString("MainFirstTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рестарт.
        /// </summary>
        public static string MainRestartBtnName {
            get {
                return ResourceManager.GetString("MainRestartBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налаштування.
        /// </summary>
        public static string MainSecondTabHeader {
            get {
                return ResourceManager.GetString("MainSecondTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старт.
        /// </summary>
        public static string MainStartBtnName {
            get {
                return ResourceManager.GetString("MainStartBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоп.
        /// </summary>
        public static string MainStopBtnName {
            get {
                return ResourceManager.GetString("MainStopBtnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Про программу.
        /// </summary>
        public static string MainThirdTabHeader {
            get {
                return ResourceManager.GetString("MainThirdTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виберіть необхідні розширення файлу.
        /// </summary>
        public static string OtherSettingsExtensions {
            get {
                return ResourceManager.GetString("OtherSettingsExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати FTP-сховище.
        /// </summary>
        public static string RepositoryStngAddFtpBtn {
            get {
                return ResourceManager.GetString("RepositoryStngAddFtpBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати локальне сховище.
        /// </summary>
        public static string RepositoryStngAddLocalBtn {
            get {
                return ResourceManager.GetString("RepositoryStngAddLocalBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налаштування репозиторія.
        /// </summary>
        public static string RepositoryStngTitle {
            get {
                return ResourceManager.GetString("RepositoryStngTitle", resourceCulture);
            }
        }
    }
}
